<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-10-23 at 05:14:51.
 * @group super
 */
class OpenStreetMapTest extends UnitTestCase
{
    var $connString;
    /**
     *
     * @var OpenStreetMap
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp ();
        if (empty ( $this->connString ))
        {
            $this->connString = Yii::app ()->db->connectionString;
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown ();
        if (empty ( Yii::app ()->db->connectionString ))
            Yii::app ()->db->connectionString = $this->connString;
    }

    /**
     * @covers OpenStreetMap::getBoundingBox
     * @group super
     */
    public function testGetBoundingBox()
    {
        $this->object = new OpenStreetMap(28.445516,  77.033508);
        $data = $this->object->getBoundingBox(500);
        $this->assertEquals($data,array (
                    'south' => 28.441066000000003,
                    'west' => 77.02840336624125,
                    'north' => 28.449966,
                    'east' => 77.03861263375875,
                    'northwest' =>
                    array (
                        'lat' => 28.449966,
                        'long' => 77.02840336624125,
                    ),
                    'northeast' =>
                    array (
                        'lat' => 28.449966,
                        'long' => 77.03861263375875,
                    ),
                    'southeast' =>
                    array (
                        'lat' => 28.441066000000003,
                        'long' => 77.03861263375875,
                    ),
                    'southwest' =>
                    array (
                        'lat' => 28.441066000000003,
                        'long' => 77.02840336624125,
                    ),
                    ));
    }

       /**
     * @covers OpenStreetMap::getBoundingBox
     * @group super
     */
    public function testGetBoundingXML()
    {
        $this->object = new OpenStreetMap(28.612808,   77.231126);
        $data = $this->object->getBoundingBoxXML(500);
        $this->assertEquals($data,'<bbox-query s="28.608358" w="77.226012689487" n="28.617258" e="77.236239310513"/>');
    }

    public function testBusStops()
    {
        $this->object = new OpenStreetMap(22.563514, 88.351056);
        $data = $this->object->getPOIs('highway','bus_stop',2000);

        $this->assertEquals($data,'<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API 0.7.55.3 9da5e7ae">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base=""/>

  <node id="1983542778" lat="22.5549476" lon="88.3647845">
    <tag k="bus" v="yes"/>
    <tag k="highway" v="bus_stop"/>
    <tag k="name" v="Jora Girja"/>
    <tag k="public_transport" v="platform"/>
  </node>
  <node id="4170884119" lat="22.5504286" lon="88.3628561">
    <tag k="highway" v="bus_stop"/>
    <tag k="name" v="nonapukur"/>
  </node>
  <node id="4183313094" lat="22.5610521" lon="88.3506582">
    <tag k="highway" v="bus_stop"/>
  </node>
  <node id="4523697907" lat="22.5563202" lon="88.3583221">
    <tag k="highway" v="bus_stop"/>
    <tag k="name" v="Taltala bazar"/>
    <tag k="name:en" v="Taltala bazar"/>
  </node>
  <node id="5465037942" lat="22.5651791" lon="88.3397666">
    <tag k="bus" v="yes"/>
    <tag k="highway" v="bus_stop"/>
    <tag k="name" v="Babu Ghat"/>
    <tag k="public_transport" v="platform"/>
  </node>

</osm>
');
    }

    public function testHospitals()
    {
        $this->object = new OpenStreetMap(  13.009340,   80.259038);
        $this->assertTrue(isset($this->object->hospitals));
        $data = $this->object->hospitals;
        $this->assertEquals(
            trim(file_get_contents(__DIR__ . '/../fixtures/poi.xml')),
            trim($this->object->dom->saveXML() ));
    }

    public function testXyz()
    {
        $this->object = new OpenStreetMap(  13.009340,   80.259038);
        $this->assertFalse(isset($this->object->xyz));

        #echo "returned: " . $data;
        #$this->assertEquals($data,'');
    }

    public function testParse()
    {
        $xml = file_get_contents(__DIR__ . '/../fixtures/poi.xml');
        $this->object = new OpenStreetMap(  13.009340,   80.259038);
        $this->object->setxml($xml);
        $data = $this->object->parsePOIs();
        $this->assertEquals("ABC",$data['ABC']['id']);
    }


}